# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ccc <- function(x, y) {
    .Call(`_concordancer_rcpp_ccc`, x, y)
}

